### ISSUE TITLE
Add tests that the examples actually work and improve pre-commit

### ISSUE THREAD

**Issue by pseudo-rnd-thoughts** [Farama-Foundation/gym-examples#8]
Currently, there is no testing that the examples actually work as we claim they do
In addition, to improve code quality, it might be worth adding to the pre-commit pydocstyle, flake8, etc

**Comment by axb2035** [comment]
@pseudo-rnd-thoughts where you say "there is no testing" are you meaning there are no automated tests as part of any update or tutorials/example code that uses gym-example?

If the latter, perhaps this issue should be split into two separete tasks?

**Comment by pseudo-rnd-thoughts** [comment]
@axb2035 Thanks for offering however we are not using gym-example now that gymnasium exists
